### PR TITLE
fix ECONNRESET

### PR DESCRIPTION
**Pull request by killa123**
fix socket destory,use [destroySoon](https://github.com/nodejs/node/blob/v8.9.3/lib/net.js#L523) instead of req.socket.destory
  if destory writing socket, it will cause ECONNRESET.

### CODE REVIEW

**Comment by dougwilson** [comment]
Thank you so much for your pull request! I'm not really sure what the issue is you're addressing though. Right now it is req.destroy because we _want_ the ECONNRESET to happen. Can you explain why your opinion is different?

**Comment by killa123** [comment]
@dougwilson  In your test [should terminate on error](https://github.com/pillarjs/finalhandler/blob/master/test/test.js#L462),when an error is thrown before response end, you except status code is 301, body is '0',not the ECONNRESET.

In some scenario, some error will be thrown when the response is end, the HTTP request is succeeded, why ECONNRESET should happen, and the actual error has not return or print.

**Comment by dougwilson** [comment]
Hi @killa123 thanks for the information! That scenario we _want_ the ECONNRESET -- because an error occurring is terminal at that point, which is the design of this module. If you don't want to terminate the connection, then don't pass an error to this module's callback if you don't want to indicate an error occurred to the client.

This module doesn't print to the screen ever, because this module doesn't understand what a user may be using STDOUT / STDERR for. You can provide a function to https://github.com/pillarjs/finalhandler#optionsonerror to print out errors if you want to see them.

**Comment by killa123** [comment]
Thank you for the reply.If the behavior described in the README, it will be better.

**Pull request closed without merging**
